sudo: false

language: php

php:
  - 5.5

env:
  - DB=mysql

before_script:
  - composer self-update
  - composer install
  - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE DATABASE sulu_test;"; fi
  - php vendor/symfony-cmf/testing/bin/console doctrine:schema:create

script:
  - phpunit

install:
    - wget http://wkhtmltopdf.googlecode.com/files/wkhtmltopdf-0.9.9-static-amd64.tar.bz2
    - tar xvjf wkhtmltopdf-0.9.9-static-amd64.tar.bz2
    - sudo mv wkhtmltopdf-amd64 /usr/local/bin/wkhtmltopdf
    - sudo chmod +x /usr/local/bin/wkhtmltopdf
