sudo: false

language: php

php:
  - 5.5

env:
  - DB=mysql

before_script:
  - echo "memory_limit=2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update
  - composer install
  - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE DATABASE sulu_test;"; fi
  - php vendor/symfony-cmf/testing/bin/console doctrine:schema:create

script:
  - phpunit

install:
    - mkdir wkhtmltopdf
    - wget https://github.com/wkhtmltopdf/obsolete-downloads/releases/download/linux/wkhtmltopdf-0.9.9-static-amd64.tar.bz2
    - tar xvjf wkhtmltopdf-0.9.9-static-amd64.tar.bz2 -C wkhtmltopdf
    - mv wkhtmltopdf/wkhtmltopdf-amd64 wkhtmltopdf/wkhtmltopdf
    - export PATH=$PATH:$PWD/wkhtmltopdf/
